apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: plateforme-educative
  labels:
    app: user-service
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: plateforme_educative-user-service:latest # Assurez-vous que ce nom correspond à votre image
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 3001 
        env:
        - name: NODE_ENV
          value: "development" 
        - name: PORT
          value: "3001"
        - name: SERVICE_NAME
          value: "UserServiceK8s"
        - name: DB_HOST
          value: "db-users-postgres" 
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: PG_USER_SERVICE_DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: PG_USER_SERVICE_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: PG_USER_SERVICE_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        readinessProbe:
          httpGet:
            path: / # Route de health check simple
            port: 3001
          initialDelaySeconds: 15 
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3