apiVersion: apps/v1
kind: Deployment
metadata:
  name: progress-service
  namespace: plateforme-educative
  labels:
    app: progress-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progress-service
  template:
    metadata:
      labels:
        app: progress-service
    spec:
      containers:
      - name: progress-service
        image: cof1409/plateforme-educative-progress-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3003"
        - name: SERVICE_NAME
          value: "ProgressServiceK8s"
        - name: DB_HOST
          value: "db-progress-postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: PG_PROGRESS_SERVICE_DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: PG_PROGRESS_SERVICE_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: PG_PROGRESS_SERVICE_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        readinessProbe:
          httpGet:
            path: /
            port: 3003
          initialDelaySeconds: 15
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 20