apiVersion: v1
kind: Service
metadata:
  name: progress-service
  namespace: plateforme-educative
  labels:
    app: progress-service
spec:
  ports:
  - name: http
    port: 3003
    targetPort: 3003
  selector:
    app: progress-service
  type: ClusterIP