apiVersion: v1
kind: Service
metadata:
  name: db-content-postgres 
  namespace: plateforme-educative
  labels:
    app: db-content-postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: db-content-postgres
  type: ClusterIP 