apiVersion: v1
kind: Service
metadata:
  name: db-progress-postgres 
  namespace: plateforme-educative
  labels:
    app: db-progress-postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: db-progress-postgres
  type: ClusterIP 