apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-details-db-pvc
  namespace: plateforme-educative
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard 