apiVersion: v1
kind: Service
metadata:
  name: mongo-details-db 
  namespace: plateforme-educative
  labels:
    app: mongo-details-db
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo-details-db
  type: ClusterIP