apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-users-postgres-pvc
  namespace: plateforme-educative
spec:
  accessModes:
  - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi 
  # storageClassName: standard # Généralement ok pour Minikube