apiVersion: v1
kind: Service
metadata:
  name: feedback-service
  namespace: plateforme-educative
  labels:
    app: feedback-service
spec:
  ports:
  - name: http
    port: 3005
    targetPort: 3005
  selector:
    app: feedback-service
  type: ClusterIP