apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: plateforme-educative
type: Opaque
data:
  PG_USER_SERVICE_PASSWORD: "ZGV2X3Bhc3N3b3Jk" # echo -n 'dev_password' | base64
  PG_CONTENT_SERVICE_PASSWORD: "ZGV2X3Bhc3N3b3Jk"
  PG_PROGRESS_SERVICE_PASSWORD: "ZGV2X3Bhc3N3b3Jk"
  PG_FEEDBACK_SERVICE_PASSWORD: "ZGV2X3Bhc3N3b3Jk"
  PG_RECO_SERVICE_PASSWORD: "ZGV2X3Bhc3N3b3Jk"