apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-recommendation-engine
  namespace: plateforme-educative
  labels:
    app: ai-recommendation-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-recommendation-engine
  template:
    metadata:
      labels:
        app: ai-recommendation-engine
    spec:
      containers:
      - name: ai-recommendation-engine
        image: cof1409/plateforme-educative-ai-recommendation-engine:12e4725
        imagePullPolicy: Always 
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP 
          value: "run.py" 
        - name: FLASK_ENV
          value: "development" 
        - name: RECOMMENDER_PORT 
          value: "5000"
        - name: CONTENT_SERVICE_URL_FOR_AI 
          value: "http://content-service:3002/api/content" 
        volumeMounts:
        - name: ai-feedback-storage
          mountPath: /app/user_negative_feedback.json 
          subPath: user_negative_feedback.json 
        readinessProbe:
          httpGet:
            path: /api/ai/health 
            port: 5000
          initialDelaySeconds: 45 
          periodSeconds: 30
          timeoutSeconds: 10 
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/ai/health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
      volumes:
      - name: ai-feedback-storage
        persistentVolumeClaim:
          claimName: ai-feedback-pvc
