apiVersion: v1
kind: Service
metadata:
  name: content-service
  namespace: plateforme-educative
  labels:
    app: content-service
spec:
  ports:
  - name: http
    port: 3002
    targetPort: 3002
  selector:
    app: content-service
  type: ClusterIP