name: CI/CD - AI Recommendation Engine - Build, Push & Update K8s Manifest

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ai-recommendation-engine/**'
      - '.github/workflows/ai-engine-python-ci-cd.yml'
  workflow_dispatch:

jobs:
  build-push-and-update-manifest:
    name: Build, Push Image & Update K8s Manifest for AI Recommendation Engine
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get_sha.outputs.sha_short }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACTIONS_PAT }} # UTILISER LE PAT

    - name: Get short SHA for image tag
      id: get_sha
      run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Define Docker Hub image name
      id: image_def
      run: echo "IMAGE_NAME_ON_HUB=cof1409/plateforme-educative-ai-recommendation-engine" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push AI Recommendation Engine image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: ./ai-recommendation-engine 
        file: ./ai-recommendation-engine/Dockerfile 
        push: true
        tags: |
          ${{ env.IMAGE_NAME_ON_HUB }}:latest
          ${{ env.IMAGE_NAME_ON_HUB }}:${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Update Kubernetes deployment manifest
      env:
        NEW_IMAGE_WITH_TAG: ${{ env.IMAGE_NAME_ON_HUB }}:${{ env.IMAGE_TAG }}
      run: |
        MANIFEST_FILE="kubernetes/ai-recommendation-engine/deployment.yaml"
        echo "Updating $MANIFEST_FILE with image: $NEW_IMAGE_WITH_TAG"
        awk -v IMAGE_LINE="        image: ${NEW_IMAGE_WITH_TAG}" '/image:.*cof1409\/plateforme-educative-ai-recommendation-engine:/ {print IMAGE_LINE; next} {print}' $MANIFEST_FILE > tmp_manifest.yaml && mv tmp_manifest.yaml $MANIFEST_FILE
        echo "--- Content of $MANIFEST_FILE after update: ---"
        cat $MANIFEST_FILE
        echo "--- End of $MANIFEST_FILE ---"
        git status

    - name: Commit and push manifest changes
      run: |
        git config --global user.name "GitHub Actions Bot (AIEngine)"
        git config --global user.email "chfarouk@users.noreply.github.com"
        git add kubernetes/ai-recommendation-engine/deployment.yaml
        if git diff --staged --quiet; then
          echo "Aucun changement dans le manifeste de déploiement pour ai-recommendation-engine."
        else
          git commit -m "CI: Update ai-engine K8s deployment to image tag ${{ env.IMAGE_TAG }} [skip ci]"
          git push
        fi