name: CI - Content Service Docker Build and Push

on:
  push:
    branches: [ "main" ]
    paths:
      - 'content-service/**'
      - '.github/workflows/content-service-ci.yml'
  workflow_dispatch:

jobs:
  build-and-push-content-service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Content Service image
      uses: docker/build-push-action@v5
      with:
        context: ./content-service
        file: ./content-service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/plateforme-educative-content-service:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max